#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE n8n;
    CREATE DATABASE outline;
    CREATE DATABASE outline_test;
    GRANT ALL PRIVILEGES ON DATABASE n8n TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE outline TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE outline_test TO $POSTGRES_USER;
EOSQL
